import React, { useState, useEffect } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import { generateQuotation } from "../services/api";

const QuotationResultPage = () => {
  const navigate = useNavigate();
  const location = useLocation();
  
  const [quotationData, setQuotationData] = useState(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState(null);
  const [formData, setFormData] = useState({
    productName: '',
    description: '',
    quantity: 1,
    specifications: '',
    customerType: 'individual',
    urgency: 'standard'
  });
  const [step, setStep] = useState(1); // 1: Form, 2: Results
  const [isEditing, setIsEditing] = useState(false);
  const [editedPrice, setEditedPrice] = useState('');

  // Initialize form data from props or session storage
  useEffect(() => {
    let initialData = null;
    
    // Try to get from location state first
    if (location.state?.productData) {
      const { productData, enhancedResult } = location.state;
      initialData = {
        productName: productData.productName,
        description: enhancedResult?.enhancedDescription || productData.currentDescription,
        quantity: 1,
        specifications: productData.specifications || '',
        customerType: 'individual',
        urgency: 'standard'
      };
    } else {
      // Try session storage
      try {
        const stored = sessionStorage.getItem('craftconnect_quotation_data');
        if (stored) {
          const data = JSON.parse(stored);
          initialData = {
            productName: data.productName,
            description: data.description,
            quantity: 1,
            specifications: data.specifications || '',
            customerType: 'individual',
            urgency: 'standard'
          };
        }
      } catch (e) {
        console.error('Error parsing stored quotation data:', e);
      }
    }

    if (initialData) {
      setFormData(initialData);
      // Auto-generate if we have complete data
      if (initialData.productName && initialData.description) {
        generateQuote(initialData);
      }
    }
  }, [location.state]);

  // Generate quotation
  const generateQuote = async (data = formData) => {
    if (!data.productName.trim() || !data.description.trim()) {
      setError('Product name and description are required');
      return;
    }

    setIsGenerating(true);
    setError(null);
    
    try {
      console.log('Generating quotation with data:', data);
      
      const response = await generateQuotation(data, []);
      
      if (response.success && response.data) {
        setQuotationData(response.data);
        setStep(2);
        
        // Store in session
        try {
          sessionStorage.setItem('craftconnect_quotation_result', JSON.stringify({
            formData: data,
            result: response.data,
            timestamp: new Date().toISOString()
          }));
        } catch (storageError) {
          console.warn('Failed to store quotation result:', storageError);
        }
      } else {
        throw new Error(response.error || 'Failed to generate quotation');
      }
    } catch (error) {
      console.error('Quotation generation error:', error);
      setError(error.message || 'Failed to generate quotation. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  // Handle form changes
  const handleFormChange = (field, value) => {
    setFormData(prev => ({
      ...prev,
      [field]: value
    }));
  };

  // Handle manual price adjustment
  const handlePriceEdit = () => {
    if (isEditing) {
      // Save the edited price
      const newPrice = parseFloat(editedPrice);
      if (!isNaN(newPrice) && newPrice > 0) {
        setQuotationData(prev => ({
          ...prev,
          finalPrice: newPrice,
          currency: prev.currency || 'INR'
        }));
      }
      setIsEditing(false);
    } else {
      setEditedPrice(quotationData?.finalPrice?.toString() || '');
      setIsEditing(true);
    }
  };

  // Generate PDF
  const generatePDF = () => {
    if (quotationData) {
      // Create PDF content
      const pdfContent = `
        QUOTATION
        
        Product: ${formData.productName}
        Description: ${formData.description}
        Quantity: ${formData.quantity}
        
        Final Price: ${quotationData.currency || 'INR'} ${quotationData.finalPrice}
        
        Breakdown:
        ${quotationData.breakdown ? quotationData.breakdown.map(item => `${item.label}: ${quotationData.currency || 'INR'} ${item.value}`).join('\n') : ''}
        
        Generated by CraftConnect AI
        Date: ${new Date().toLocaleDateString()}
      `;
      
      // Simple download as text file (can be enhanced to real PDF)
      const blob = new Blob([pdfContent], { type: 'text/plain' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `quotation_${formData.productName.replace(/\s+/g, '_')}.txt`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    }
  };

  // Send via WhatsApp
  const sendViaWhatsApp = () => {
    if (quotationData) {
      const message = `🎨 *QUOTATION* 🎨\n\n📦 *Product:* ${formData.productName}\n📝 *Description:* ${formData.description}\n🔢 *Quantity:* ${formData.quantity}\n\n💰 *Final Price:* ${quotationData.currency || 'INR'} ${quotationData.finalPrice}\n\n${quotationData.breakdown ? quotationData.breakdown.map(item => `• ${item.label}: ${quotationData.currency || 'INR'} ${item.value}`).join('\n') : ''}\n\n✨ Generated by CraftConnect AI\n📅 ${new Date().toLocaleDateString()}`;
      
      const encodedMessage = encodeURIComponent(message);
      const whatsappUrl = `https://wa.me/?text=${encodedMessage}`;
      window.open(whatsappUrl, '_blank');
    }
  };

  return (
    <div className="min-h-screen w-full bg-[#f8f7f6] dark:bg-[#221810] text-[#333333] dark:text-[#f8f7f6]">
      {/* Header */}
      <header className="flex items-center justify-between border-b border-[#E6E0DB] dark:border-[#443a32] px-4 sm:px-10 lg:px-20 py-4 bg-white dark:bg-[#221810]">
        <div className="flex items-center gap-4">
          <div className="text-[#E85D04] size-7">
            <svg fill="none" viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg">
              <path d="M36.7273 44C33.9891 44 31.6043 39.8386 30.3636 33.69C29.123 39.8386 26.7382 44 24 44C21.2618 44 18.877 39.8386 17.6364 33.69C16.3957 39.8386 14.0109 44 11.2727 44C7.25611 44 4 35.0457 4 24C4 12.9543 7.25611 4 11.2727 4C14.0109 4 16.3957 8.16144 17.6364 14.31C18.877 8.16144 21.2618 4 24 4C26.7382 4 29.123 8.16144 30.3636 14.31C31.6043 8.16144 33.9891 4 36.7273 4C40.7439 4 44 12.9543 44 24C44 35.0457 40.7439 44 36.7273 44Z" fill="currentColor"/>
            </svg>
          </div>
          <h2 className="text-lg font-bold tracking-[-0.015em]">Craft Connect</h2>
        </div>
        <div className="flex items-center gap-4">
          <button 
            onClick={() => navigate('/hub')} 
            className="size-10 rounded-lg bg-[#f8f7f6] dark:bg-[#221810]/50 flex items-center justify-center hover:scale-105 transition-transform"
          >
            <span className="material-symbols-outlined">home</span>
          </button>
          {step === 2 && (
            <button 
              onClick={() => setStep(1)}
              className="h-10 px-4 rounded-lg bg-[#f8f7f6] dark:bg-[#221810]/50 flex items-center justify-center text-sm font-bold hover:scale-105 transition-transform"
            >
              New Quote
            </button>
          )}
        </div>
      </header>

      <main className="px-4 sm:px-6 md:px-10 lg:px-20 py-8 flex flex-1 justify-center items-center">
        {/* Step 1: Form */}
        {step === 1 && (
          <div className="w-full max-w-2xl flex flex-col gap-6">
            <div className="text-center">
              <h1 className="text-4xl font-black tracking-[-0.033em]">AI Quotation Generator</h1>
              <p className="mt-2 text-[#333333]/80 dark:text-[#f8f7f6]/80">
                Provide product details and let AI generate a professional quotation
              </p>
            </div>

            {/* Error Message */}
            {error && (
              <div className="rounded-lg bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 p-4">
                <div className="flex items-center gap-3">
                  <span className="material-symbols-outlined text-red-500">error</span>
                  <p className="text-red-700 dark:text-red-300">{error}</p>
                </div>
              </div>
            )}

            {/* Form */}
            <div className="bg-white dark:bg-[#221810]/80 p-6 sm:p-8 rounded-xl shadow-lg border border-[#E6E0DB]/50 dark:border-[#443a32]/50 space-y-6">
              {/* Product Name */}
              <div className="space-y-2">
                <label className="block text-sm font-bold text-[#333333] dark:text-[#f8f7f6]">
                  Product Name *
                </label>
                <input
                  type="text"
                  value={formData.productName}
                  onChange={(e) => handleFormChange('productName', e.target.value)}
                  placeholder="e.g., Hand-Carved Wooden Bowl"
                  className="w-full h-12 px-4 rounded-lg border border-[#E6E0DB] dark:border-[#443a32] bg-white dark:bg-[#221810]/60 text-[#333333] dark:text-[#f8f7f6] placeholder-[#333333]/60 dark:placeholder-[#f8f7f6]/60 focus:outline-none focus:ring-2 focus:ring-[#E85D04]"
                />
              </div>

              {/* Description */}
              <div className="space-y-2">
                <label className="block text-sm font-bold text-[#333333] dark:text-[#f8f7f6]">
                  Product Description *
                </label>
                <textarea
                  value={formData.description}
                  onChange={(e) => handleFormChange('description', e.target.value)}
                  placeholder="Describe your product's features, materials, craftsmanship, and unique qualities..."
                  rows={4}
                  className="w-full px-4 py-3 rounded-lg border border-[#E6E0DB] dark:border-[#443a32] bg-white dark:bg-[#221810]/60 text-[#333333] dark:text-[#f8f7f6] placeholder-[#333333]/60 dark:placeholder-[#f8f7f6]/60 focus:outline-none focus:ring-2 focus:ring-[#E85D04] resize-none"
                />
              </div>

              {/* Quantity */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <label className="block text-sm font-bold text-[#333333] dark:text-[#f8f7f6]">
                    Quantity *
                  </label>
                  <input
                    type="number"
                    min="1"
                    value={formData.quantity}
                    onChange={(e) => handleFormChange('quantity', parseInt(e.target.value) || 1)}
                    className="w-full h-12 px-4 rounded-lg border border-[#E6E0DB] dark:border-[#443a32] bg-white dark:bg-[#221810]/60 text-[#333333] dark:text-[#f8f7f6] focus:outline-none focus:ring-2 focus:ring-[#E85D04]"
                  />
                </div>

                {/* Customer Type */}
                <div className="space-y-2">
                  <label className="block text-sm font-bold text-[#333333] dark:text-[#f8f7f6]">
                    Customer Type
                  </label>
                  <select
                    value={formData.customerType}
                    onChange={(e) => handleFormChange('customerType', e.target.value)}
                    className="w-full h-12 px-4 rounded-lg border border-[#E6E0DB] dark:border-[#443a32] bg-white dark:bg-[#221810]/60 text-[#333333] dark:text-[#f8f7f6] focus:outline-none focus:ring-2 focus:ring-[#E85D04]"
                  >
                    <option value="individual">Individual</option>
                    <option value="business">Business</option>
                    <option value="wholesale">Wholesale</option>
                    <option value="corporate">Corporate</option>
                  </select>
                </div>
              </div>

              {/* Specifications */}
              <div className="space-y-2">
                <label className="block text-sm font-bold text-[#333333] dark:text-[#f8f7f6]">
                  Additional Specifications (Optional)
                </label>
                <textarea
                  value={formData.specifications}
                  onChange={(e) => handleFormChange('specifications', e.target.value)}
                  placeholder="Size dimensions, color preferences, customization requests, delivery requirements..."
                  rows={3}
                  className="w-full px-4 py-3 rounded-lg border border-[#E6E0DB] dark:border-[#443a32] bg-white dark:bg-[#221810]/60 text-[#333333] dark:text-[#f8f7f6] placeholder-[#333333]/60 dark:placeholder-[#f8f7f6]/60 focus:outline-none focus:ring-2 focus:ring-[#E85D04] resize-none"
                />
              </div>

              {/* Urgency */}
              <div className="space-y-2">
                <label className="block text-sm font-bold text-[#333333] dark:text-[#f8f7f6]">
                  Urgency
                </label>
                <div className="grid grid-cols-3 gap-3">
                  {['standard', 'urgent', 'rush'].map((urgency) => (
                    <button
                      key={urgency}
                      onClick={() => handleFormChange('urgency', urgency)}
                      className={`h-12 px-4 rounded-lg font-bold text-sm transition-colors ${
                        formData.urgency === urgency
                          ? 'bg-[#E85D04] text-white'
                          : 'bg-[#f8f7f6] dark:bg-[#221810]/60 text-[#333333] dark:text-[#f8f7f6] hover:bg-[#E6E0DB]/40 dark:hover:bg-[#443a32]/40'
                      }`}
                    >
                      {urgency.charAt(0).toUpperCase() + urgency.slice(1)}
                    </button>
                  ))}
                </div>
              </div>

              {/* Generate Button */}
              <button
                onClick={() => generateQuote()}
                disabled={isGenerating || !formData.productName.trim() || !formData.description.trim()}
                className={`w-full h-14 rounded-lg font-bold text-lg transition-all ${
                  isGenerating || !formData.productName.trim() || !formData.description.trim()
                    ? 'bg-gray-400 cursor-not-allowed text-gray-600'
                    : 'bg-[#E85D04] hover:bg-[#d4560c] text-white hover:scale-[1.02] active:scale-[0.98]'
                }`}
              >
                {isGenerating ? (
                  <div className="flex items-center justify-center gap-3">
                    <div className="animate-spin size-6 border-2 border-white border-t-transparent rounded-full"></div>
                    Generating AI Quotation...
                  </div>
                ) : (
                  '🤖 Generate AI Quotation'
                )}
              </button>
            </div>
          </div>
        )}

        {/* Step 2: Results */}
        {step === 2 && quotationData && (
          <div className="w-full max-w-2xl flex flex-col gap-6">
            <div className="text-center">
              <h1 className="text-4xl font-black tracking-[-0.033em]">AI Generated Quotation</h1>
              <p className="mt-2 text-[#333333]/80 dark:text-[#f8f7f6]/80">
                Review your AI-generated quotation. You can adjust, finalize, and send it directly to your client.
              </p>
            </div>

            <div className="bg-white dark:bg-[#221810]/80 p-6 sm:p-8 rounded-xl shadow-lg border border-[#E6E0DB]/50 dark:border-[#443a32]/50 flex flex-col gap-6">
              <div className="text-center">
                <h2 className="text-2xl font-bold tracking-[-0.015em]">{formData.productName}</h2>
                <p className="mt-1 text-[#333333]/80 dark:text-[#f8f7f6]/80 max-w-prose mx-auto">
                  {quotationData.aiDescription || formData.description}
                </p>
                <div className="mt-2 flex flex-wrap items-center justify-center gap-2 text-sm">
                  <span className="bg-[#f8f7f6] dark:bg-[#221810]/60 px-3 py-1 rounded-full">Qty: {formData.quantity}</span>
                  <span className="bg-[#f8f7f6] dark:bg-[#221810]/60 px-3 py-1 rounded-full">{formData.customerType}</span>
                  <span className="bg-[#f8f7f6] dark:bg-[#221810]/60 px-3 py-1 rounded-full">{formData.urgency}</span>
                </div>
              </div>

              <div className="rounded-lg p-6 text-center bg-[#FFF8F0] dark:bg-[#E85D04]/10">
                <p className="text-sm font-medium uppercase tracking-wider text-[#333333]/70 dark:text-[#f8f7f6]/70">
                  Final Suggested Price
                </p>
                {isEditing ? (
                  <div className="mt-2 flex items-center justify-center gap-2">
                    <span className="text-3xl font-extrabold text-[#E85D04]">₹</span>
                    <input
                      type="number"
                      value={editedPrice}
                      onChange={(e) => setEditedPrice(e.target.value)}
                      className="text-4xl sm:text-5xl font-extrabold text-[#E85D04] bg-transparent border-b-2 border-[#E85D04] text-center w-32 focus:outline-none"
                      autoFocus
                    />
                  </div>
                ) : (
                  <p className="mt-2 text-6xl sm:text-7xl font-extrabold text-[#E85D04] leading-none">
                    ₹{quotationData.finalPrice?.toLocaleString() || '0'}
                  </p>
                )}
              </div>

              {/* Breakdown */}
              {quotationData.breakdown && quotationData.breakdown.length > 0 && (
                <div>
                  <h3 className="text-lg font-bold tracking-[-0.015em] pb-4 border-b border-[#E6E0DB] dark:border-[#443a32]">
                    Detailed Breakdown
                  </h3>
                  <div className="pt-4 space-y-4">
                    {quotationData.breakdown.map((item, index) => (
                      <div key={index} className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <span className="material-symbols-outlined text-base text-[#333333]/60 dark:text-[#f8f7f6]/60">
                            {item.icon || 'attach_money'}
                          </span>
                          <p className="font-medium">{item.label}</p>
                        </div>
                        <p className="text-lg font-bold">₹{item.value?.toLocaleString() || '0'}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Action Buttons */}
              <div className="pt-4 border-t border-[#E6E0DB] dark:border-[#443a32] flex flex-col sm:flex-row gap-3">
                <button 
                  onClick={handlePriceEdit}
                  className="w-full sm:w-auto flex-1 h-12 px-6 rounded-lg font-bold bg-[#f8f7f6] dark:bg-[#221810] border-2 border-[#E6E0DB] dark:border-[#443a32] text-[#333333] dark:text-[#f8f7f6] hover:bg-[#E6E0DB]/40 dark:hover:bg-[#443a32]/40 flex items-center justify-center gap-2"
                >
                  <span className="material-symbols-outlined text-xl">{isEditing ? 'save' : 'edit'}</span>
                  {isEditing ? 'Save Price' : 'Adjust Price'}
                </button>
                <button 
                  onClick={generatePDF}
                  className="w-full sm:w-auto h-12 px-6 rounded-lg font-bold border-2 border-[#E85D04] text-[#E85D04] hover:bg-[#E85D04]/10 flex items-center justify-center gap-2"
                >
                  <span className="material-symbols-outlined text-xl">picture_as_pdf</span>
                  Generate Invoice
                </button>
                <button 
                  onClick={sendViaWhatsApp}
                  className="w-full sm:w-auto h-12 px-6 rounded-lg font-bold bg-[#E85D04] text-white hover:scale-105 shadow-md hover:shadow-lg transition-transform flex items-center justify-center gap-2"
                >
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" viewBox="0 0 16 16">
                    <path d="M13.601 2.326A7.85 7.85 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.9 7.9 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.9 7.9 0 0 0 13.6 2.326zM7.994 14.521a6.6 6.6 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.56 6.56 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592m3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.73.73 0 0 0-.529.247c-.182.198-.691.677-.691 1.654s.71 1.916.81 2.049c.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943s-.182-.133-.38-.232"/>
                  </svg>
                  Send via WhatsApp
                </button>
              </div>
            </div>
          </div>
        )}
      </main>
    </div>
  );
};

export default QuotationResultPage;