import React, { useState, useEffect } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import { generateQuotation } from "../services/api";
import PageHeader from "../components/layout/PageHeader";
import Card from "../components/ui/Card";
import Button from "../components/ui/Button";
import Spinner from "../components/ui/Spinner";

const QuotationResultPage = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const [quotationData, setQuotationData] = useState(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState(null);
  const [formData, setFormData] = useState({ productName: '', description: '', quantity: 1, specifications: '', customerType: 'individual', urgency: 'standard' });
  const [step, setStep] = useState(1);
  const [isEditing, setIsEditing] = useState(false);
  const [editedPrice, setEditedPrice] = useState('');

  useEffect(() => {
    let initial = null;
    if (location.state?.productData) {
      const { productData, enhancedResult } = location.state;
      initial = { productName: productData.productName, description: enhancedResult?.enhancedDescription || productData.currentDescription, quantity: 1, specifications: productData.specifications || '', customerType: 'individual', urgency: 'standard' };
    } else {
      const stored = sessionStorage.getItem('craftconnect_quotation_data');
      if (stored) { try { const d = JSON.parse(stored); initial = { productName: d.productName, description: d.description, quantity: 1, specifications: d.specifications || '', customerType: 'individual', urgency: 'standard' }; } catch {} }
    }
    if (initial) { setFormData(initial); if (initial.productName && initial.description) generateQuote(initial); }
  }, [location.state]);

  const generateQuote = async (data = formData) => {
    if (!data.productName.trim() || !data.description.trim()) return setError('Product name and description are required');
    setIsGenerating(true); setError(null);
    try {
      const response = await generateQuotation(data, []);
      if (response.success && response.data) { setQuotationData(response.data); setStep(2); sessionStorage.setItem('craftconnect_quotation_result', JSON.stringify({ formData: data, result: response.data, ts: Date.now() })); }
      else throw new Error(response.error || 'Failed to generate quotation');
    } catch (e) { setError(e.message || 'Failed to generate quotation. Please try again.'); }
    finally { setIsGenerating(false); }
  };

  const handleFormChange = (field, value) => setFormData(prev => ({ ...prev, [field]: value }));
  const handlePriceEdit = () => { if (isEditing) { const val = parseFloat(editedPrice); if (!isNaN(val) && val > 0) setQuotationData(prev => ({ ...prev, finalPrice: val, currency: prev?.currency || 'INR' })); setIsEditing(false); } else { setEditedPrice(quotationData?.finalPrice?.toString() || ''); setIsEditing(true); } };
  const generateTextInvoice = () => {
    if (!quotationData) return;
    const txt = `QUOTATION\n\nProduct: ${formData.productName}\nDescription: ${formData.description}\nQuantity: ${formData.quantity}\n\nFinal Price: ${quotationData.currency || 'INR'} ${quotationData.finalPrice}\n\n${quotationData.breakdown ? quotationData.breakdown.map(i => `${i.label}: ${quotationData.currency || 'INR'} ${i.value}`).join('\n') : ''}\n\nGenerated by CraftConnect AI\nDate: ${new Date().toLocaleDateString()}`;
    const blob = new Blob([txt], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `quotation_${formData.productName.replace(/\s+/g, '_')}.txt`; document.body.appendChild(a); a.click(); window.URL.revokeObjectURL(url); document.body.removeChild(a);
  };
  const shareViaWhatsApp = () => { if (!quotationData) return; const msg = `🎨 *QUOTATION* 🎨\n\n📦 *Product:* ${formData.productName}\n📝 *Description:* ${formData.description}\n🔢 *Quantity:* ${formData.quantity}\n\n💰 *Final Price:* ${quotationData.currency || 'INR'} ${quotationData.finalPrice}\n\n${quotationData.breakdown ? quotationData.breakdown.map(i => `• ${i.label}: ${quotationData.currency || 'INR'} ${i.value}`).join('\n') : ''}\n\n✨ Generated by CraftConnect AI\n📅 ${new Date().toLocaleDateString()}`; const encoded = encodeURIComponent(msg); window.open(`https://wa.me/?text=${encoded}`, '_blank'); };

  return (
    <div className="min-h-screen w-full bg-[#f8f7f6]">
      <PageHeader title="AI Quotation Generator" subtitle="Professional quotes with editable pricing" onBack={() => setStep(1)} actions={step === 2 ? [<Button key="new" variant="muted" onClick={() => setStep(1)}>New Quote</Button>] : []} />

      <main className="px-4 sm:px-6 lg:px-8 py-8 flex justify-center">
        <div className="w-full max-w-3xl space-y-6">
          {step === 1 && (
            <Card className="space-y-6">
              {error && (
                <div className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-rose-700 flex items-center gap-2">
                  <span className="material-symbols-outlined">error</span>
                  <span>{error}</span>
                </div>
              )}

              <div>
                <label className="block text-sm font-bold mb-2">Product Name *</label>
                <input type="text" value={formData.productName} onChange={(e) => handleFormChange('productName', e.target.value)} placeholder="e.g., Hand-Carved Wooden Bowl" className="w-full h-12 px-4 rounded-lg border focus:ring-2 focus:ring-[#ec6d13]" />
              </div>

              <div>
                <label className="block text-sm font-bold mb-2">Product Description *</label>
                <textarea value={formData.description} onChange={(e) => handleFormChange('description', e.target.value)} placeholder="Describe features, materials, craftsmanship..." rows={4} className="w-full px-4 py-3 rounded-lg border focus:ring-2 focus:ring-[#ec6d13] resize-none" />
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-bold mb-2">Quantity *</label>
                  <input type="number" min="1" value={formData.quantity} onChange={(e) => handleFormChange('quantity', parseInt(e.target.value) || 1)} className="w-full h-12 px-4 rounded-lg border focus:ring-2 focus:ring-[#ec6d13]" />
                </div>
                <div>
                  <label className="block text-sm font-bold mb-2">Customer Type</label>
                  <select value={formData.customerType} onChange={(e) => handleFormChange('customerType', e.target.value)} className="w-full h-12 px-4 rounded-lg border focus:ring-2 focus:ring-[#ec6d13]">
                    <option value="individual">Individual</option>
                    <option value="business">Business</option>
                    <option value="wholesale">Wholesale</option>
                    <option value="corporate">Corporate</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-sm font-bold mb-2">Additional Specifications</label>
                <textarea value={formData.specifications} onChange={(e) => handleFormChange('specifications', e.target.value)} placeholder="Size, color, customization, delivery requirements..." rows={3} className="w-full px-4 py-3 rounded-lg border focus:ring-2 focus:ring-[#ec6d13] resize-none" />
              </div>

              <div>
                <label className="block text-sm font-bold mb-2">Urgency</label>
                <div className="grid grid-cols-3 gap-3">
                  {['standard', 'urgent', 'rush'].map((u) => (
                    <Button key={u} variant={formData.urgency === u ? 'primary' : 'muted'} onClick={() => handleFormChange('urgency', u)}>
                      {u.charAt(0).toUpperCase() + u.slice(1)}
                    </Button>
                  ))}
                </div>
              </div>

              <Button onClick={() => generateQuote()} disabled={isGenerating || !formData.productName.trim() || !formData.description.trim()} className="w-full">
                {isGenerating ? (<span className="flex items-center gap-2"><Spinner/> Generating...</span>) : '🤖 Generate AI Quotation'}
              </Button>
            </Card>
          )}

          {step === 2 && quotationData && (
            <div className="space-y-6">
              <Card>
                <div className="text-center">
                  <h2 className="text-2xl font-bold">{formData.productName}</h2>
                  <p className="mt-1 text-slate-700 max-w-prose mx-auto">{quotationData.aiDescription || formData.description}</p>
                  <div className="mt-2 flex flex-wrap items-center justify-center gap-2 text-sm">
                    <span className="bg-slate-100 px-3 py-1 rounded-full">Qty: {formData.quantity}</span>
                    <span className="bg-slate-100 px-3 py-1 rounded-full">{formData.customerType}</span>
                    <span className="bg-slate-100 px-3 py-1 rounded-full">{formData.urgency}</span>
                  </div>
                </div>
              </Card>

              <Card className="text-center bg-[#FFF8F0]">
                <p className="text-xs font-medium uppercase tracking-wider text-slate-600">Final Suggested Price</p>
                {isEditing ? (
                  <div className="mt-2 flex items-center justify-center gap-2">
                    <span className="text-3xl font-extrabold text-[#ec6d13]">₹</span>
                    <input type="number" value={editedPrice} onChange={(e) => setEditedPrice(e.target.value)} className="text-4xl font-extrabold text-[#ec6d13] bg-transparent border-b-2 border-[#ec6d13] text-center w-32 focus:outline-none" autoFocus />
                  </div>
                ) : (
                  <p className="mt-2 text-6xl font-extrabold text-[#ec6d13] leading-none">₹{quotationData.finalPrice?.toLocaleString() || '0'}</p>
                )}
              </Card>

              {quotationData.breakdown?.length > 0 && (
                <Card>
                  <h3 className="text-lg font-bold mb-3">Detailed Breakdown</h3>
                  <div className="space-y-3">
                    {quotationData.breakdown.map((i, idx) => (
                      <div key={idx} className="flex items-center justify-between">
                        <div className="flex items-center gap-2 text-slate-700">
                          <span className="material-symbols-outlined text-base text-slate-500">{i.icon || 'attach_money'}</span>
                          <p className="font-medium">{i.label}</p>
                        </div>
                        <p className="text-lg font-bold">₹{i.value?.toLocaleString() || '0'}</p>
                      </div>
                    ))}
                  </div>
                </Card>
              )}

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                <Button onClick={() => { setIsEditing(!isEditing); if (isEditing) setEditedPrice(''); }}>
                  {isEditing ? 'Save Price' : 'Adjust Price'}
                </Button>
                <Button variant="secondary" onClick={generateTextInvoice}>Generate Invoice</Button>
                <Button variant="success" onClick={shareViaWhatsApp}>Share via WhatsApp</Button>
              </div>
            </div>
          )}
        </div>
      </main>
    </div>
  );
};

export default QuotationResultPage;
